name: Build and Publish Release for arm64

on:
  workflow_dispatch:

jobs:
  build_and_publish_release:
    runs-on: ubuntu-latest 

    env:
      RELEASE_NAME: opengnb_arm64_1.4.5.b

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: gnbdev/opengnb
          ref: ver1.4.5.b  # 指定要检出的分支或提交

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Install ARM64 cross-compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: Build binary
        run: |
          export CC=aarch64-linux-gnu-gcc
          sed -i 's|\(CC} -o ${GNB_CTL} ${GNB_CTL_OBJS} ${CLI_LDFLAGS}\)|\1 -static|' Makefile.linux
          sed -i 's|\(CC} -o ${GNB_ES} ${GNB_ES_OBJS} ${CRYPTO_OBJS} ${MINIUPNP_OBJS} ${LIBNATPMP_OBJS} ${GNB_ES_LDFLAGS}\)|\1 -static|' Makefile.linux
          sed -i 's|\(CC} -o ${GNB_CRYPTO} ./src/gnb_crypto.o ${CRYPTO_OBJS} ${CLI_LDFLAGS}\)|\1 -static|' Makefile.linux
          sed -i 's|\(CC} -o ${GNB_CLI} ${GNB_OBJS} ${GNB_CLI_OBJS} ${GNB_PF_OBJS} ${CRYPTO_OBJS} ${ZLIB_OBJS} ${CLI_LDFLAGS}\)|\1 -static|' Makefile.linux
          make -f Makefile.linux clean
          make -f Makefile.linux install 
        shell: bash
      
      - name: Build and Package
        run: |
          mkdir release
          cp -r examples/node_config_example conf
          cp -r bin release/
          cp -r conf release/
          tar -czvf ${{ env.RELEASE_NAME }}.tar.gz -C release .
        shell: bash
        
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
            files: ${{ env.RELEASE_NAME }}.tar.gz
            tag_name: v1.4.5.b  # 你的版本号 
            body: | 
              Release notes for v1.4.5.b
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
