name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_release:
    runs-on: ubuntu-latest

    env:
      RELEASE_NAME: opengnb_arm64_lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: gnbdev/opengnb
          ref: master  # 指定要检出的分支或提交

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Build binary
        run: GOARCH=arm64 make -f Makefile.linux install
        shell: bash
      
      - name: Build and Package
        run: |
          mkdir release
          cp -r examples/node_config_example conf
          cp -r bin release/
          cp -r conf release/
          tar -czvf opengnb_arm64_lastest.tar.gz -C release .
        shell: bash
        
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
            files: opengnb_arm64_lastest.tar.gz
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
